CREATE TABLE `articles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`instagramPostId` varchar(128) NOT NULL,
	`title` varchar(512) NOT NULL,
	`slug` varchar(512) NOT NULL,
	`caption` text NOT NULL,
	`content` text,
	`thumbnailUrl` varchar(512),
	`instagramImageUrl` varchar(512),
	`mediaType` varchar(32),
	`mediaUrl` varchar(512),
	`likeCount` int NOT NULL DEFAULT 0,
	`commentCount` int NOT NULL DEFAULT 0,
	`permalink` varchar(512),
	`publishedAt` timestamp,
	`isPublished` boolean NOT NULL DEFAULT true,
	`seoTitle` varchar(160),
	`seoDescription` varchar(160),
	`keywords` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `articles_id` PRIMARY KEY(`id`),
	CONSTRAINT `articles_instagramPostId_unique` UNIQUE(`instagramPostId`),
	CONSTRAINT `articles_slug_unique` UNIQUE(`slug`)
);
