import { Link } from "wouter";
import { SiteNav } from "@/components/SiteNav";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { getLoginUrl } from "@/const";
import { toast } from "sonner";
import { Check, CircleDollarSign, Loader2, ShieldAlert, X } from "lucide-react";

const money = (value: number) => `$${(value / 100).toFixed(2)}`;

export default function AdminBeatPayouts() {
  const { user, loading } = useAuth();
  const utils = trpc.useUtils();
  const { data: payouts = [], isLoading } = trpc.beats.admin.payouts.useQuery(undefined, { enabled: user?.role === "admin" });
  const setStatus = trpc.beats.admin.setPayoutStatus.useMutation({ onSuccess: () => { utils.beats.admin.payouts.invalidate(); toast.success("Payout updated."); }, onError: (error) => toast.error(error.message) });
  if (loading || (user?.role === "admin" && isLoading)) return <div className="min-h-screen bg-[#080808]"><SiteNav /><div className="grid min-h-screen place-items-center"><Loader2 className="h-7 w-7 animate-spin text-red-500" /></div></div>;
  if (!user) return <div className="min-h-screen bg-[#080808] text-white"><SiteNav /><div className="container pt-36 text-center"><ShieldAlert className="mx-auto h-10 w-10 text-red-500" /><p className="mt-4 text-white/60">Sign in to access administration.</p><a href={getLoginUrl("/admin/beats")} className="mt-5 inline-block bg-red-600 px-5 py-3 text-xs font-bold uppercase tracking-widest">Sign in</a></div></div>;
  if (user.role !== "admin") return <div className="min-h-screen bg-[#080808] text-white"><SiteNav /><div className="container pt-36 text-center"><ShieldAlert className="mx-auto h-10 w-10 text-red-500" /><h1 className="mt-4 font-['Anton'] text-3xl uppercase">Admin access only</h1></div></div>;
  return <div className="min-h-screen bg-[#080808] text-white"><SiteNav /><main className="container pt-28 pb-20"><div className="flex flex-col justify-between gap-4 border-b border-white/10 pb-6 md:flex-row md:items-end"><div><p className="text-[10px] font-black uppercase tracking-[.3em] text-red-500">Marketplace admin</p><h1 className="mt-2 font-['Anton'] text-5xl uppercase">BEAT PAYOUTS</h1><p className="mt-2 text-sm text-white/50">Review and record producer marketplace payout requests.</p></div><Link href="/admin" className="border border-white/20 px-4 py-3 text-xs font-black uppercase tracking-widest text-white/60 hover:text-white">Admin panel</Link></div><div className="mt-7 space-y-3">{payouts.length ? payouts.map(({ request, producer }) => <article key={request.id} className="flex flex-col gap-5 border border-white/10 bg-[#101010] p-5 lg:flex-row lg:items-center"><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold">{producer?.artistName || producer?.name || `Producer #${request.producerId}`}</h2><span className={`border px-2 py-1 text-[9px] font-black uppercase tracking-widest ${request.status === "paid" ? "border-green-500/30 text-green-400" : request.status === "pending" ? "border-yellow-500/30 text-yellow-300" : "border-white/15 text-white/45"}`}>{request.status}</span></div><p className="mt-2 text-sm text-white/55">{money(request.amountCents)} · {request.paymentMethod.toUpperCase()} · {request.paymentHandle}</p><p className="mt-1 text-xs text-white/32">Requested {new Date(request.createdAt).toLocaleString()}{request.adminNote ? ` · ${request.adminNote}` : ""}</p></div>{request.status === "pending" || request.status === "approved" ? <div className="flex flex-wrap gap-2"><button onClick={() => setStatus.mutate({ id: request.id, status: "approved" })} disabled={setStatus.isPending} className="flex items-center gap-2 border border-blue-400/40 px-3 py-2 text-[10px] font-black uppercase tracking-widest text-blue-300 hover:bg-blue-400/10"><Check className="h-3.5 w-3.5" />Approve</button><button onClick={() => setStatus.mutate({ id: request.id, status: "paid" })} disabled={setStatus.isPending} className="flex items-center gap-2 bg-green-600 px-3 py-2 text-[10px] font-black uppercase tracking-widest hover:bg-green-500"><CircleDollarSign className="h-3.5 w-3.5" />Mark paid</button><button onClick={() => setStatus.mutate({ id: request.id, status: "rejected" })} disabled={setStatus.isPending} className="flex items-center gap-2 border border-red-500/40 px-3 py-2 text-[10px] font-black uppercase tracking-widest text-red-300 hover:bg-red-500/10"><X className="h-3.5 w-3.5" />Reject</button></div> : null}</article>) : <div className="border border-dashed border-white/15 py-16 text-center text-sm text-white/40">No producer payout requests yet.</div>}</div></main></div>;
}
