import { buildBeatLicenseContractText, type ContractSnapshot } from "../shared/beat-marketplace";

function pdfEscape(value: string) {
  return value
    .replace(/[\\]/g, "\\\\")
    .replace(/[()]/g, "\\$&")
    .replace(/[^\x20-\x7E]/g, " ");
}

function wrapLine(value: string, maxLength = 92) {
  const words = value.replace(/\s+/g, " ").trim().split(" ");
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    const candidate = current ? `${current} ${word}` : word;
    if (candidate.length > maxLength && current) {
      lines.push(current);
      current = word;
    } else {
      current = candidate;
    }
  }
  if (current) lines.push(current);
  return lines;
}

/** Builds a compact, printable PDF license without an external runtime dependency. */
export function buildBeatLicensePdf(snapshot: ContractSnapshot) {
  const amount = `$${(snapshot.amountCents / 100).toFixed(2)} USD`;
  const body = buildBeatLicenseContractText(snapshot);
  const lines = [
    "MURDER MITTEN MEDIA",
    "BEAT LICENSE AGREEMENT",
    `Contract: ${snapshot.contractNumber}`,
    `Effective: ${snapshot.effectiveDate}`,
    "",
    `Producer: ${snapshot.producerName}${snapshot.producerEmail ? ` (${snapshot.producerEmail})` : ""}`,
    `Artist / Buyer: ${snapshot.buyerName}${snapshot.buyerEmail ? ` (${snapshot.buyerEmail})` : ""}`,
    `Beat: ${snapshot.beatTitle}`,
    `License: ${snapshot.license.name}`,
    `Price Paid: ${amount}`,
    "",
    ...body.flatMap((paragraph) => {
      const isHeading = /^[A-Z &]+\.$/.test(paragraph);
      return isHeading ? ["", paragraph] : wrapLine(paragraph);
    }),
    "",
    "Marketplace record generated by Murder Mitten Media.",
  ];

  const chunks: string[][] = [];
  for (let index = 0; index < lines.length; index += 43) chunks.push(lines.slice(index, index + 43));

  const objects: string[] = [];
  const addObject = (value: string) => {
    objects.push(value);
    return objects.length;
  };

  const catalogId = addObject("");
  const pagesId = addObject("");
  const fontId = addObject("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
  const pageIds: number[] = [];
  const streamIds: number[] = [];

  for (const chunk of chunks) {
    const streamLines = chunk.map((line, index) => {
      const y = 760 - index * 16;
      const bold = /^[A-Z &]+\.$/.test(line) || line === "MURDER MITTEN MEDIA" || line === "BEAT LICENSE AGREEMENT";
      return `${bold ? "/F1 10 Tf" : "/F1 9 Tf"} 1 0 0 1 54 ${y} Tm (${pdfEscape(line)}) Tj`;
    });
    const stream = `BT\n${streamLines.join("\n") }\nET`;
    const streamId = addObject(`<< /Length ${Buffer.byteLength(stream, "utf8")} >>\nstream\n${stream}\nendstream`);
    streamIds.push(streamId);
    const pageId = addObject("");
    pageIds.push(pageId);
  }

  pageIds.forEach((pageId, index) => {
    objects[pageId - 1] = `<< /Type /Page /Parent ${pagesId} 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 ${fontId} 0 R >> >> /Contents ${streamIds[index]} 0 R >>`;
  });
  objects[pagesId - 1] = `<< /Type /Pages /Kids [${pageIds.map((id) => `${id} 0 R`).join(" ")}] /Count ${pageIds.length} >>`;
  objects[catalogId - 1] = `<< /Type /Catalog /Pages ${pagesId} 0 R >>`;

  let pdf = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(Buffer.byteLength(pdf, "utf8"));
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xrefOffset = Buffer.byteLength(pdf, "utf8");
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (let index = 1; index < offsets.length; index += 1) {
    pdf += `${String(offsets[index]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root ${catalogId} 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;
  return Buffer.from(pdf, "utf8");
}
